#!/usr/bin/env bash

# Unlink the ffs alias if it links to ffsend
if [[ -L /usr/bin/ffs ]] \
    && [[ $(realpath /usr/bin/ffs) == "/usr/bin/ffsend" ]]; \
then
    echo "Removing ffs alias for ffsend..."
    unlink /usr/bin/ffs
fi
